% This is an autogenerated sample test for all
classdef tSimulateModel < matlab.unittest.TestCase
    methods (Test)
        function testAll(testCase)
            % Specify the inputs
            sObj=SimulationModel
            sObj.simulate
            %isa(sObj.SimData,'SimData')
            testCase.verifyClass(sObj.SimData,'SimData')
            import matlab.unittest.constraints.IsSameSetAs
            testCase.verifyThat(sObj.SimData.DataNames,...
                IsSameSetAs(["Drug","Receptor","Complex","RO"]))

        end
    end
end